### ISSUE TITLE
nvcc: not found

### ISSUE THREAD

**Issue by supersupercoconut** [ispc-lab/LiDAR4D#3]
在按照教程进行安装的过程中，出现了nvcc: not found的错误。ubuntu20.04之前没有安装过cuda，但是这里却出现了这种错误

(lidar4d) supercoconut@supercoconut:~/Myfile/LiDAR4D/tiny-cuda-nn/bindings/torch$ python setup.py install
/home/supercoconut/Myfile/LiDAR4D/tiny-cuda-nn/bindings/torch/setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
Building PyTorch extension for tiny-cuda-nn version 1.7
Obtained compute capability 89 from PyTorch
sh: 1: nvcc: not found
Targeting C++ standard 14
running install
/home/supercoconut/anaconda3/envs/lidar4d/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/supercoconut/anaconda3/envs/lidar4d/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating tinycudann.egg-info
writing tinycudann.egg-info/PKG-INFO
writing dependency_links to tinycudann.egg-info/dependency_links.txt
writing top-level names to tinycudann.egg-info/top_level.txt
writing manifest file 'tinycudann.egg-info/SOURCES.txt'
/home/supercoconut/anaconda3/envs/lidar4d/lib/python3.9/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'tinycudann.egg-info/SOURCES.txt'
writing manifest file 'tinycudann.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-39
creating build/lib.linux-x86_64-cpython-39/tinycudann
copying tinycudann/modules.py -> build/lib.linux-x86_64-cpython-39/tinycudann
copying tinycudann/__init__.py -> build/lib.linux-x86_64-cpython-39/tinycudann
copying tinycudann/bindings.cpp -> build/lib.linux-x86_64-cpython-39/tinycudann
running build_ext
error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'

**Comment by dyfcalid** [comment]
Tiny-cuda-nn requires GPU and CUDA. So you need to install CUDA first and then add the CUDA installation to your PATH. For more detailed instruction, you can refer to https://github.com/NVlabs/tiny-cuda-nn.

**Comment by supersupercoconut** [comment]
感谢回复！我之前以为这个命令(pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118)是安装cuda，原来是安装pytorch的。我已经成功运行了您开源的代码，并且将自己的安装过程整理到了一个[CSDN博客](https://blog.csdn.net/weixin_46116156/article/details/138132120?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22138132120%22%2C%22source%22%3A%22weixin_46116156%22%7D)中,但是我现在还有一些疑问：

1. 请问这个算法输出结果只有一些图片么？能否类似于论文中Fig.1，可以展示整个数据集中自身车辆的周围重建结果。
2. github中的时间线是不是有些问题，是2023而不是2024么。
![image](https://github.com/ispc-lab/LiDAR4D/assets/137087582/3942a5eb-3d4b-4406-9ffc-2e0bc937c3e7)

**Comment by supersupercoconut** [comment]
感谢回复！我之前以为这个命令(pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118) 是安装cuda，原来是安装pytorch的。

我已经成功运行了您开源的代码，并且将自己的安装过程整理到了一个[CSDN博客](https://blog.csdn.net/weixin_46116156/article/details/138132120?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22138132120%22%2C%22source%22%3A%22weixin_46116156%22%7D) 中, 但是我现在还有一些疑问：

1. 请问这个算法输出结果只有一些图片么？能否类似于论文中Fig.1，可以展示整个数据集中自身车辆的周围重建结果。
2. github中的时间线是不是有些问题，是2023而不是2024么。
![image](https://github.com/ispc-lab/LiDAR4D/assets/137087582/3942a5eb-3d4b-4406-9ffc-2e0bc937c3e7)

**Comment by dyfcalid** [comment]
Thank you for your blog! 👍
1. The Fig.1 in the paper is just the original point cloud, in order to show the dynamic scene. And the model will automatically save novel-view reconstructed results of depth/intensity/raydrop images (`*.png`) and corresponding point clouds (`*.npy`) in the `results` filefolder. Btw, we may update some codes of the LiDAR simulator later for easier rendering, so stay tuned.
2. Thanks. We will revise it in the next update.
