### ISSUE TITLE
points error

### ISSUE THREAD

**Issue by roseupram** [ispc-lab/LiDAR4D#4]
Thanks for your works. I'm testing on KITTI-360, I found the synthesized point stored as .npy. So I use this to convert it to pcd. 
```
import numpy as np
import open3d as op

path = "./log/kitti360_lidar4d_f4950_release/results/test_lidar4d_ep0639_0002_depth_lidar.npy"
points = np.load(path)
print(points.shape,points[:10])
pcd = op.geometry.PointCloud()
pcd.points = op.utility.Vector3dVector(points)
op.io.write_point_cloud("2.pcd",pcd)
```
But it looks like the depths are wrong. Below image is captured from pcl_viewer
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/4f9375a7-83dc-4536-b08c-728314061472)
Below image is corresponding depth map
![test_lidar4d_ep0639_0002_depth](https://github.com/ispc-lab/LiDAR4D/assets/59827483/8d40d341-9cc5-422a-9e97-702415d27262)
This is the output of evaluation
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/007c5b23-829e-46e8-8956-320e959f6b9c)
Could you please help me find where is wrong?

**Comment by dyfcalid** [comment]
Hi, there.
The results of the evaluation are wrong, but the depth map looks normal. It seems that the depth scale is not correct. You can check if the data is preprocessed in the right way. We have provided an example `kitti360_4950.txt` in the `configs` folder, and the `scale` is about 0.01. 
If the problem is still not solved, you can follow the instructions to double-check each step, or offer me more details.

**Comment by roseupram** [comment]
this is the kitti360_4950.txt
```
dataloader = kitti360
path = data/kitti360
sequence_id = 4950
num_frames = 51
fov_lidar = [2.0, 26.9]
scale = 0.010504329815187737
offset = [1307.2250542680918, 3604.6116677769596, 110.30188369430098]
```
this is the command I run, I have trained it for 639 epoch
```
main_lidar4d.py \
--config configs/kitti360_4950.txt \
--workspace log/kitti360_lidar4d_f4950_release \
--lr 1e-2 \
--num_rays_lidar 1024 \
--iters 30000 \
--alpha_d 1 \
--alpha_i 0.1 \
--alpha_r 0.01 \
--test_eval 
```
before the code converting depth to lidar, I find the pred_depth's values span a narrow range from 0.199 to 0.201. 
```
pred_lidar = pano_to_lidar(
                    pred_depth / self.opt.scale, loader._data.intrinsics_lidar
                )
```
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/e0ef96d9-fbdf-4a4e-8655-3ebce29638f2)

I do not know how to solve this 
Can you provide some instructions to double-check , or what details should I offer?

**Comment by dyfcalid** [comment]
It's weird, and I've never encountered it before. Could you provide information about your machine and environment, as well as the training and evaluation log (first and last several epochs)?

**Comment by roseupram** [comment]
Yes, that's so weird. I remove all checkpoints and train again. It looks normal. Thans for your help. 
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/601491d4-4e26-40a8-b937-4874976c3d7b)
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/4ca12b7d-f83e-471f-95cf-4a7603e3aa3a)

# last question
Could you provide your code for visualization, or which library do you use to visualize?
Like this, that's more pretty.
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/8675ecb9-3288-437c-844d-7b27a6133d6b)

**Comment by dyfcalid** [comment]
OK.👌 You can try `open3d` for visualization and customize the color.

**Comment by Petros626** [comment]
@roseupram does the authors provide any `.ckpt` files? or do we have to train from scratch?

**Comment by roseupram** [comment]
@Petros626 seems not provided

**Comment by Petros626** [comment]
@roseupram thank you for the quick answer.

With which dataset you trained the model? Could you share your `.ckpt` file in case of using this repo? I try to avoid training from scratch.

**Comment by roseupram** [comment]
@Petros626  I use `KITTI-360` in README.
Sorry, I open this issue 1 year ago, now I am not doing research on this.
So all related files had been deleted to clean disk space.

**Comment by Petros626** [comment]
@roseupram okay I understand, nevertheless thanks for the information.

Maybe in case of using this repo, I could come back to you?

**Comment by roseupram** [comment]
@Petros626 Sure, feel free to reach out anytime!
