### ISSUE TITLE
Some questions about the kitti360 dataset

### ISSUE THREAD

**Issue by lipeng-gu** [ispc-lab/LiDAR4D#7]
Hi,

This is excellent work. I am very grateful for your sharing.
However, I see that the experiments were conducted by training and testing on each sequence individually. How were the final metrics obtained? In other words, were all the experiments in this paper conducted using scene 4950 from the sequence 2013_05_28_drive_0000 for both training and testing? Or were there other setups?

**Comment by dyfcalid** [comment]
We conduct experiments on multiple scenarios, taking the average value as the final result. For example, on the KITTI-360 dynamic dataset, we select the sequences `2350` `4950` `8120` `10200` `10750` `11400`. For each scene, some intermediate frames are selected for testing and the remaining for training. It can be found in the [preprocess code](https://github.com/ispc-lab/LiDAR4D/blob/2c73ba6a1272d05a2176ce2d3cede361e28a3d9e/data/preprocess/kitti360_to_nerf.py#L19). Modify the `SEQ_ID` in `preprocess_data.sh` and the `--config` in `run_kitti_lidar4d.sh` to run different scenarios.

**Comment by lipeng-gu** [comment]
I am very grateful for your response. I would like to follow your work in the future, and if there is an opportunity, we can collaborate and exchange ideas.

**Comment by dyfcalid** [comment]
I’m glad to hear that, and you can feel free to drop me an [email](mailto:zhengzehan@tongji.edu.cn) if there are any questions or further communication. Thank you for your interest again! 😄
