### ISSUE TITLE
About the SEQ_ID number of the kitti-360 dataset

### ISSUE THREAD

**Issue by booker-max** [ispc-lab/LiDAR4D#8]
In your readme.md, you mentioned SEQ_IDs such as 2350, 4950, 8120, 10200, 10750, 11400. How do I obtain these? I directly downloaded the Raw Velodyne Scans data, but it seems that I didn't see any information about SEQ_IDs.
![image](https://github.com/user-attachments/assets/b9b78840-f068-489e-af34-7dcb6da162fd)
The official website provides the following information:
![image](https://github.com/user-attachments/assets/12835480-02bb-4f0f-9a8a-41870ae2d0cf)
![image](https://github.com/user-attachments/assets/748f651c-606a-45c9-b3f9-61f407d280b3)
So, are my SEQ_IDs 0000, 0002, 0003, 0004, and 0005?"

**Comment by dyfcalid** [comment]
Sorry for the ambiguity. We use `2013_05_28_drive_0000_sync` for the experiments. And the `SEQ_ID` actually refers to the frame index. Once you download the dataset, you can run `preprocess_data.sh` to obtain the corresponding training data.

**Comment by booker-max** [comment]
Thank you.
