### ISSUE TITLE
how to set the pano height and pano width

### ISSUE THREAD

**Issue by booker-max** [ispc-lab/LiDAR4D#9]
对于kitti360数据集，在生成rangeview的过程中，你设置pano height=66, pano width=1030, 想问下这个是怎么得到的，因为我想要用我自己的lidar数据，这两个参数是和什么有关
![image](https://github.com/user-attachments/assets/ff68e935-e4c7-4566-9733-64e3ca47f429)

**Comment by dyfcalid** [comment]
Thank you for your question!
The height is associated with the number of LiDAR beams and the width is related to the LiDAR angular resolution. 
We set the parameter in the figure to keep it consistent with the LiDAR-NeRF, but you can modify it for general applications. For example, for a 32-beam LiDAR with 1024 points per ring, you can set `H=32` and `W=1024`.

**Comment by booker-max** [comment]
Thank you for your prompt reply
